steps:

- name: gcr.io/cloud-builders/gsutil
  args: ['cp gs://${_STATE_BUCKET}/keys/*.json .']
  id: copy keys
  dir: 'keys'

# Bootstrap
- name: hashicorp/terraform
  args: ['init']
  id: bootstrap init
  dir: 'terraform/0-bootstrap'
  waitFor: ['copy keys']

- name: hashicorp/terraform
  id: bootstrap plan
  args: ['plan', '-auto-approve', '-lock=false']
  dir: 'terraform/0-bootstrap'
  waitFor: ['bootstrap init']

- name: hashicorp/terraform
  id: bootstrap apply
  args: ['apply', '-auto-approve', '-lock=false']
  dir: 'terraform/0-bootstrap'
  waitFor: ['bootstrap plan']